#!/bin/sh
# /usr/bin/gen-storage-labels.sh - friendly names for Status -> Overview -> Storage.
# Builds a LuCI status include that renames "/dev/xxx (/mnt/yyy)" rows to "<disk model> — <purpose>"
# and hides noise: Docker container layers, ujail tmpfs and repeat mounts of the same disk.
# Purposes are taken from /etc/storage-labels ("/mnt/point|Text" per line), defaults below.
# Run at boot (rc.local), after the disks are mounted.
OUT=/www/luci-static/resources/view/status/include/26_storage_labels.js
CONF=/etc/storage-labels

purpose() {
	p=$(grep -m1 "^$1|" "$CONF" 2>/dev/null | cut -d'|' -f2-)
	[ -n "$p" ] && { echo "$p"; return; }
	case "$1" in
		/mnt/nvme) echo "Docker, Home Assistant" ;;
		/mnt/ssd2) echo "данные, статистика" ;;
		*) echo "${1#/mnt/}" ;;
	esac
}

model() { # /dev/nvme1n1p1 -> "Samsung SSD 980 PRO 2TB"
	b=${1#/dev/}
	[ -e /sys/class/block/$b/partition ] && b=$(basename "$(readlink -f /sys/class/block/$b/..)")
	m=$(sed 's/ *$//' /sys/class/block/$b/device/model 2>/dev/null)
	case "$m" in "") echo "$b" ;; *SSD*|*ssd*) echo "$m" ;; *) echo "SSD $m" ;; esac
}

esc() { sed 's/\\/\\\\/g; s/"/\\"/g'; }

map="" hide="" seen=""
# shortest mount point first, so repeat mounts of a disk (bind mounts) come later and get hidden
awk '$1 ~ /^\/dev\// && $2 ~ /^\/mnt\// { print length($2), $1, $2 }' /proc/mounts | sort -n |
while read -r _ dev mp; do
	key="$dev ($mp)"
	case " $seen " in
		*" $dev "*) echo "H	$key" ;;
		*) seen="$seen $dev"; echo "L	$key	$(model "$dev") — $(purpose "$mp")" ;;
	esac
done > /tmp/.storage-labels.$$

while IFS='	' read -r kind key label; do
	k=$(printf '%s' "$key" | esc)
	if [ "$kind" = H ]; then hide="$hide	\"$k\",
"; else map="$map	\"$k\": \"$(printf '%s' "$label" | esc)\",
"; fi
done < /tmp/.storage-labels.$$
rm -f /tmp/.storage-labels.$$

cat > "$OUT.tmp" <<JS
'use strict';
'require baseclass';

/* Generated by /usr/bin/gen-storage-labels.sh - friendly names for the Storage table. */

var MAP = {
	"Disk space": "Система (eMMC)",
	"Дисковое пространство": "Система (eMMC)",
	"Temp space": "Оперативная память (/tmp)",
	"Временное хранилище": "Оперативная память (/tmp)",
$map};
var HIDE = [
$hide];
var HIDE_RE = [ /^overlay \(\/.*\/overlayfs\//, /^tmpfs \(\/tmp\/\.ujail\)/ ];

function relabel() {
	var tds = document.querySelectorAll('td.td.left'), i, td, t, j, hidden;
	for (i = 0; i < tds.length; i++) {
		td = tds[i];
		if (td.children.length) continue;
		t = td.textContent.trim();
		hidden = HIDE.indexOf(t) >= 0;
		for (j = 0; !hidden && j < HIDE_RE.length; j++) hidden = HIDE_RE[j].test(t);
		if (hidden) { if (td.parentNode.style.display != 'none') td.parentNode.style.display = 'none'; continue; }
		if (MAP[t]) { td.title = t; td.textContent = MAP[t]; }
	}
}

var observer = null;

return baseclass.extend({
	title: null,
	render: function() {
		if (!observer) {
			observer = new MutationObserver(relabel);
			observer.observe(document.body, { childList: true, subtree: true });
		}
		relabel();
		return null;
	}
});
JS
mv "$OUT.tmp" "$OUT"
