#!/bin/sh
# /usr/bin/gen-temp-labels.sh - builds human-readable names for the luci-app-temp-status widget
# (Status -> Overview -> Temperature) from the actual hardware, and writes them as a LuCI status
# include that relabels the widget in the browser. Run at boot (rc.local): hwmon numbers can change.
OUT=/www/luci-static/resources/view/status/include/28_temp_labels.js

map=""
add() { map="$map	\"$1\": \"$2\",
"; }

add "cpu_thermal / temp1" "CPU (MT7988A)"

# Wi-Fi: hwmon mt7996_phy0.N belongs to the radio with option radio='N'
for s in $(uci -q show wireless | sed -n "s/^wireless\.\([^.]*\)=wifi-device$/\1/p"); do
	n=$(uci -q get wireless.$s.radio) || continue
	case "$(uci -q get wireless.$s.band)" in
		2g) b="2.4 GHz" ;; 5g) b="5 GHz" ;; 6g) b="6 GHz" ;; *) continue ;;
	esac
	add "mt7996_phy0.$n / temp1" "Wi-Fi $b"
done

# Ethernet PHYs with a temperature sensor: map mdio_bus:X_mii:YY to the port using it
for d in /sys/class/net/*; do
	[ -e "$d/phydev" ] || continue
	p=$(readlink -f "$d/phydev")
	add "$(basename "$p" | tr '-' '_') / temp1" "Port $(basename "$d") PHY"
done

# SFP cages
for s in /sys/class/hwmon/hwmon*/name; do
	case "$(cat "$s")" in sfp*) n=$(cat "$s"); add "$n / temperature" "SFP${n#sfp} module" ;; esac
done

# NVMe: models in hwmon order (the widget lists sensors in hwmon order)
nvme=""
i=0
while [ $i -lt 64 ]; do
	h=/sys/class/hwmon/hwmon$i
	if [ -r $h/name ] && [ "$(cat $h/name)" = nvme ]; then
		m=$(sed 's/ *$//' $h/device/model 2>/dev/null)
		case "$m" in *SSD*) ;; *) m="SSD ${m:-NVMe}" ;; esac
		nvme="$nvme\"$m\", "
	fi
	i=$((i + 1))
done

cat > "$OUT.tmp" <<JS
'use strict';
'require baseclass';

/* Generated by /usr/bin/gen-temp-labels.sh - renames luci-app-temp-status sensors. */

var MAP = {
$map};
var NVME = [ $nvme];
var RE = /^(cpu_thermal|mt7996_phy\d+\.\d+|sfp\d+|mdio_bus:[\w:.]+|nvme) \/ (.+)\$/;

function relabel() {
	var w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT), n, nv = -1;
	while ((n = w.nextNode())) {
		var t = n.data.trim(), m = RE.exec(t), l = null;
		if (NVME.indexOf(t) >= 0) { nv = NVME.indexOf(t); continue; }
		if (!m) continue;
		if (MAP[t]) l = MAP[t];
		else if (m[1] == 'nvme') {
			if (m[2] == 'Composite') nv++;
			var d = NVME[Math.max(nv, 0)] || 'SSD';
			l = (m[2] == 'Composite') ? d : d + ' (' + m[2].toLowerCase() + ')';
		}
		if (l) n.data = n.data.replace(t, l);
	}
}

var observer = null;

return baseclass.extend({
	title: null,
	render: function() {
		if (!observer) {
			observer = new MutationObserver(relabel);
			observer.observe(document.body, { childList: true, subtree: true });
		}
		relabel();
		return null;
	}
});
JS
mv "$OUT.tmp" "$OUT"
