#!/bin/sh
# /usr/bin/gen-temp-labels.sh - builds human-readable names for the luci-app-temp-status widget
# (Status -> Overview -> Temperature) from the actual hardware, and writes them as a LuCI status
# include that relabels the widget in the browser and colours each sensor green/yellow/red. Run at boot (rc.local): hwmon numbers can change.
OUT=/www/luci-static/resources/view/status/include/28_temp_labels.js

map=""
add() { map="$map	\"$1\": \"$2\",
"; }

add "cpu_thermal / temp1" "CPU (MT7988A)"

# Wi-Fi: hwmon mt7996_phy0.N belongs to the radio with option radio='N'
for s in $(uci -q show wireless | sed -n "s/^wireless\.\([^.]*\)=wifi-device$/\1/p"); do
	n=$(uci -q get wireless.$s.radio) || continue
	case "$(uci -q get wireless.$s.band)" in
		2g) b="2.4 GHz" ;; 5g) b="5 GHz" ;; 6g) b="6 GHz" ;; *) continue ;;
	esac
	add "mt7996_phy0.$n / temp1" "Wi-Fi $b"
done

# Ethernet PHYs with a temperature sensor: the PHY device links to its port via attached_dev
# (fallback: the port's phydev link, then the port's DT phy-handle == the PHY's DT phandle)
for h in /sys/class/hwmon/hwmon*; do
	case "$(cat $h/name)" in mdio*) ;; *) continue ;; esac
	port=""
	[ -e $h/device/attached_dev ] && port=$(basename "$(readlink -f $h/device/attached_dev)")
	if [ -z "$port" ]; then
		for d in /sys/class/net/*; do
			[ -e "$d/phydev" ] && [ "$(readlink -f "$d/phydev")" = "$(readlink -f $h/device)" ] && port=$(basename "$d")
		done
	fi
	ph=$(hexdump -v -e '/1 "%02x"' $h/device/of_node/phandle 2>/dev/null)
	if [ -z "$port" ] && [ -n "$ph" ]; then
		for d in /sys/class/net/*; do
			[ "$(hexdump -v -e '/1 "%02x"' "$d/of_node/phy-handle" 2>/dev/null)" = "$ph" ] && port=$(basename "$d")
		done
	fi
	[ -n "$port" ] && add "$(cat $h/name) / temp1" "Port $port PHY" || add "$(cat $h/name) / temp1" "Switch PHY ${h##*hwmon}"
done

# SFP cages
for s in /sys/class/hwmon/hwmon*/name; do
	case "$(cat "$s")" in sfp*) n=$(cat "$s"); add "$n / temperature" "SFP${n#sfp} module" ;; esac
done

# NVMe: models in hwmon order (the widget lists sensors in hwmon order)
nvme=""
i=0
while [ $i -lt 64 ]; do
	h=/sys/class/hwmon/hwmon$i
	if [ -r $h/name ] && [ "$(cat $h/name)" = nvme ]; then
		m=$(sed 's/ *$//' $h/device/model 2>/dev/null)
		case "$m" in *SSD*) ;; *) m="SSD ${m:-NVMe}" ;; esac
		nvme="$nvme\"$m\", "
	fi
	i=$((i + 1))
done

cat > "$OUT.tmp" <<JS
'use strict';
'require baseclass';

/* Generated by /usr/bin/gen-temp-labels.sh - renames luci-app-temp-status sensors. */

var MAP = {
$map};
var NVME = [ $nvme];
var RE = /^(cpu_thermal|mt7996_phy\d+\.\d+|sfp\d+|mdio_bus:[\w:.]+|nvme) \/ (.+)\$/;

function relabel() {
	var w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT), n, nv = -1;
	while ((n = w.nextNode())) {
		var t = n.data.trim(), m = RE.exec(t), l = null;
		if (NVME.indexOf(t) >= 0) { nv = NVME.indexOf(t); continue; }
		if (!m) continue;
		if (MAP[t]) l = MAP[t];
		else if (m[1] == 'nvme') {
			if (m[2] == 'Composite') nv++;
			var d = NVME[Math.max(nv, 0)] || 'SSD';
			l = (m[2] == 'Composite') ? d : d + ' (' + m[2].toLowerCase() + ')';
		}
		if (l) n.data = n.data.replace(t, l);
	}
}

/* Colour coding: each value becomes a bar (like the memory bars) coloured green / yellow / red
 * by per-sensor-type thresholds [warm, hot] in °C; the fill shows how close it is to "hot". */
var LEVELS = [
	[ /^CPU/,           70, 85 ],
	[ /SSD|NVMe/,       55, 70 ],
	[ /PHY/,            70, 90 ],
	[ /^SFP/,           60, 75 ],
	[ /^Wi-Fi/,         70, 90 ]
];
var DEFAULT_LEVEL = [ 60, 80 ];
var CLASSES = [ 'tl-green', 'tl-yellow', 'tl-red' ];

var CSS = [
	'.tl-green  { --tl-a: #16a34a; --tl-b: #4ade80; --tl-t: rgba(34, 197, 94, 0.16); --tl-g: rgba(34, 197, 94, 0); }',
	'.tl-yellow { --tl-a: #ca8a04; --tl-b: #facc15; --tl-t: rgba(234, 179, 8, 0.18); --tl-g: rgba(234, 179, 8, 0); }',
	'.tl-red    { --tl-a: #dc2626; --tl-b: #f87171; --tl-t: rgba(239, 68, 68, 0.20); --tl-g: rgba(239, 68, 68, 0.55); }',
	'.tl-bar {',
	'	display: block; box-sizing: border-box; min-width: 7em; height: 1.75em; line-height: 1.75em;',
	'	border-radius: 999px; overflow: hidden; text-align: center; white-space: nowrap;',
	'	color: #fff !important; font-weight: 600; font-variant-numeric: tabular-nums;',
	'	text-shadow: 0 1px 2px rgba(0, 0, 0, 0.45);',
	'	background: linear-gradient(90deg, var(--tl-a), var(--tl-b)) 0 0 / var(--tl-pct, 0%) 100% no-repeat, var(--tl-t);',
	'	transition: background-size .8s ease; }',
	'.temp-status-temp-value.tl-bar { display: inline-block; width: 7em; margin-right: .25em; vertical-align: middle; }',
	'.tl-red .tl-bar, .tl-bar.tl-red { animation: tl-glow 1.6s ease-in-out infinite; }',
	'@keyframes tl-glow { 0%, 100% { box-shadow: 0 0 0 0 var(--tl-g); } 50% { box-shadow: 0 0 10px 2px var(--tl-g); } }'
].join('\n');

function level(name) {
	for (var i = 0; i < LEVELS.length; i++)
		if (LEVELS[i][0].test(name)) return LEVELS[i];
	return [ null, DEFAULT_LEVEL[0], DEFAULT_LEVEL[1] ];
}

function paintItem(box, nameEl, valEl) {
	if (!box || !nameEl || !valEl) return;
	var bar = valEl, t = parseFloat(valEl.textContent), lv = level(nameEl.textContent.trim()), c, i;
	/* table view: wrap the value into a bar; list view: the value span becomes the bar */
	if (valEl.tagName == 'TD') {
		bar = valEl.querySelector('.tl-bar');
		if (!bar) {
			if (isNaN(t)) return;
			bar = E('span', { 'class': 'tl-bar' }, valEl.textContent.trim());
			valEl.textContent = '';
			valEl.appendChild(bar);
		}
	}
	if (isNaN(t)) {
		bar.classList.remove.apply(bar.classList, CLASSES.concat([ 'tl-bar' ]));
		return;
	}
	c = (t >= lv[2]) ? 2 : (t >= lv[1]) ? 1 : 0;
	bar.classList.add('tl-bar');
	for (i = 0; i < CLASSES.length; i++)
		bar.classList.toggle(CLASSES[i], i == c);
	/* fill: 25 °C = empty, 10 °C above "hot" = full */
	var pct = Math.max(4, Math.min(100, (t - 25) * 100 / (lv[2] + 10 - 25)));
	bar.style.setProperty('--tl-pct', pct.toFixed(0) + '%');
	bar.title = 'норма < ' + lv[1] + ' °C, тепло ' + lv[1] + '–' + lv[2] + ' °C, горячо ≥ ' + lv[2] + ' °C';
}

function paint() {
	var i, l = document.querySelectorAll('.temp-status-list-item');
	for (i = 0; i < l.length; i++)
		paintItem(l[i], l[i].querySelector('.temp-status-sensor-name'), l[i].querySelector('.temp-status-temp-value'));
	l = document.querySelectorAll('tr[data-path]');
	for (i = 0; i < l.length; i++)
		paintItem(l[i], l[i].children[0], l[i].children[1]);
}

function update() {
	relabel();
	paint();
}

var observer = null;

return baseclass.extend({
	title: null,
	render: function() {
		if (!observer) {
			document.head.appendChild(E('style', { 'type': 'text/css' }, CSS));
			observer = new MutationObserver(update);
			observer.observe(document.body, { childList: true, subtree: true });
		}
		update();
		return null;
	}
});
JS
mv "$OUT.tmp" "$OUT"
